development:
  adapter: postgresql
  encoding: utf8
  database: reservester_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: reservester_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: reservester_production
  pool: 5
  username: 
  password: